services:
  app:
    build: .
    container_name: pokewall-arm
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-include *
    environment:
      - USER_TABLE_NAME=${USER_TABLE_NAME}
      - DATA_DIR=${DATA_DIR}
      - API_KEY_LENGTH=${API_KEY_LENGTH}
    ports:
      - 8000:8000
    volumes:
      - .:/app
