name: Build and Deploy Container Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
              DATA_DIR=${{ secrets.DATA_DIR}}
              USER_TABLE_NAME=${{ secrets.USER_TABLE_NAME }}
              API_KEY_LENGTH=${{ secrets.API_KEY_LENGTH }}
          push: false
          tags: pokewallacr.azurecr.io/app/pokewallapp:latest

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://pokewallacr.azurecr.io/
          username: ${{ secrets.ACRUSERNAME }}
          password: ${{ secrets.ACRPASSWORD }}

      - name: Push Docker Image to Registry
        run: docker push pokewallacr.azurecr.io/app/pokewallapp:latest
