name: Build and Deploy Container Image

on:
  push:
    branches:
      - main

env:
  DATA_DIR: ./data
  USER_TABLE_NAME: users
  API_KEY_LENGTH: 16

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://pokewallacr.azurecr.io/
          username: ${{ secrets.ACRUSERNAME }}
          password: ${{ secrets.ACRPASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            DATA_DIR=$DATA_DIR
            USER_TABLE_NAME=$USER_TABLE_NAME
            API_KEY_LENGTH=$API_KEY_LENGTH
          push: false
          tags: pokewallacr.azurecr.io/app/pokewallapp:latest


      - name: Push Docker Image to Registry
        run: docker push pokewallacr.azurecr.io/app/pokewallapp:latest