# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pokewallapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pokewallacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cb80d0525ed0447aa0e194556c8554cb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1d1f0a38811f467a8dcb855d1eba24bb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pokewallacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cb80d0525ed0447aa0e194556c8554cb }}/app/pokewallapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pokewallapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_47fb38790a814d96b265476cbf722467 }}
        images: 'pokewallacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cb80d0525ed0447aa0e194556c8554cb }}/app/pokewallapp:${{ github.sha }}'