# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pokewallapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pokewallacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_470fdea7eaa7487ca1523b82b2af33fb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_03d248787f0242feb3b5afc3fe5a7f0d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pokewallacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_470fdea7eaa7487ca1523b82b2af33fb }}/pokewall-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pokewallapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e916b75ce55a4a9dba50c9599506a2af }}
        images: 'pokewallacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_470fdea7eaa7487ca1523b82b2af33fb }}/pokewall-app:${{ github.sha }}'